version: '2'
services:
    maybebug-app:
        image: maybebug
        external_links:
            - maybebug-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/maybebug?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    maybebug-mysql:
        extends:
            file: mysql.yml
            service: maybebug-mysql
